[workspace]
resolver = "2"
members = [
    "squash",
    "squash-derive"
]

[workspace.dependencies]
thiserror = "1.0"
serde = { version = "1.0" , features = ["derive"] }
derive_more = { version = "1.0", features = ["full"] }
ux = "0.1"

syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"